### ISSUE TITLE
no import os in adaptors.py

### ISSUE THREAD

**Issue by RubenRBakker** [pyQms/pyqms#6]
Hi,

If adapters.py (this github repo) gets a unrecognized file format supplied the line 325 `os.path.splitext(evidence_file)[1]` is executed. However, nowhere in the script it says import os, so by adding that it will execute without issues. Unless I am mistaken somehow and am using the wrong installment / repo.

**Comment by MKoesters** [comment]
Hi Ruben, 
Thanks for reporting this, I'll push a fix tomorrow with the fix for your other Issue :)

**Comment by MKoesters** [comment]
Fixed with #7
